### ISSUE TITLE
Cannot change the wallpaper

### ISSUE THREAD

**Issue by ibnesayeed** [elementary/wallpapers#61] opened 2018-10-20 19:43 UTC
Changing wallpaper does not seem to be working on my machine. The default wallpaper remains applied no matter which one is selected in the wallpaper switcher window. I also tried to see system logs to identify any issues, but I am not sure if there is a specific place where I should be looking for it. As a side note, I am using a two monitor desktop setup and my home drive is network-mounted. I can provide further details on demand.

![wallpaper-change-issue](https://user-images.githubusercontent.com/65147/47259860-58779580-d47e-11e8-9a8c-da0488a5166a.png)

**Comment by cassidyjames** [comment] 2018-10-20 20:02
Thanks for reporting! This appears to be a duplicate of https://github.com/elementary/gala/issues/13

**Closed by cassidyjames** 2018-10-20 20:02 UTC
